In [1]:
import torch
import time

device = 'cpu'

In [2]:
randint = torch.randint(-100, 100, (6, 5))
randint

tensor([[-98,  76, -90, -18,  81],
        [ 42,  72,  48, -32,  96],
        [-70,   0,  -3,  84, -95],
        [-10, -38,   2,  -6,  16],
        [ 76,  87, -97,  49, -42],
        [ 57,  87,  31, -91,  86]])

In [3]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
ones = torch.ones(5, 6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [5]:
tensor = torch.tensor([[2, 3, 5], [4, 6, 3], [0, 4, 6]], dtype=torch.float)
tensor

tensor([[2., 3., 5.],
        [4., 6., 3.],
        [0., 4., 6.]])

In [6]:
empty = torch.empty(6)
empty

tensor([-1.9994e-38,  3.0774e-41, -1.9998e-38,  3.0774e-41,  8.9683e-44,
         0.0000e+00])

In [7]:
arange = torch.arange(9)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
linspace = torch.linspace(-3, 24, steps=9)
linspace

tensor([-3.0000,  0.3750,  3.7500,  7.1250, 10.5000, 13.8750, 17.2500, 20.6250,
        24.0000])

In [9]:
logspace = torch.logspace(-3, 24, steps=9)
logspace

tensor([1.0000e-03, 2.3714e+00, 5.6234e+03, 1.3335e+07, 3.1623e+10, 7.4989e+13,
        1.7783e+17, 4.2170e+20, 1.0000e+24])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)

start = time.time()

rand = (torch_rand1 @ torch_rand2)

end = time.time()

elapsed_time = end - start

print(f"{elapsed_time:.10f}")

0.2660877705


In [12]:
%%time

torch_rand1 = torch.rand(50, 50, 50, 50).to(device)
torch_rand2 = torch.rand(50, 50, 50, 50).to(device)

rand = (torch_rand1 @ torch_rand2)


CPU times: user 281 ms, sys: 90.4 ms, total: 371 ms
Wall time: 91.7 ms


In [15]:
# Define a probability tensor
probability = torch.tensor([0.1, 0.9])

# This will give us the samples with the probability, ie. 0 will come with probability of 10% and 1 will come with probability of 90%...
samples = torch.multinomial(probability, num_samples=20, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [17]:
probability = torch.tensor([0.5, 0.5])
samples = torch.multinomial(probability, num_samples=20, replacement=True)
print(samples)

tensor([1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0])


In [19]:
t = torch.tensor([1, 2, 3, 4, 5])
out = torch.cat((t, torch.tensor([6])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6])

In [20]:
p = torch.tril(torch.ones((5, 5)))
p

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
q = torch.triu(torch.ones((6, 6)))
q

tensor([[1., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.]])

In [24]:
r = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
r

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [26]:
torch.exp(r) # e raised to above function...

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [32]:
s = torch.zeros(2, 3, 4)
t = s.transpose(0, 2) # Replaces 0th dimension with 2nd dimension...
print(s.shape)
print(t.shape)

torch.Size([2, 3, 4])
torch.Size([4, 3, 2])


In [33]:
u = torch.ones(3, 4, 6, 7)
v = u.transpose(1, 2).transpose(0, 3)
print(u.shape)
print(v.shape)

torch.Size([3, 4, 6, 7])
torch.Size([7, 6, 4, 3])
